name: Benchmark cache
on:
  push:
    branches:
      - cache-test

jobs:
  save_cache:
    name: ${{ matrix.runner }}
    strategy:
      matrix:
        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        runner: [ubuntu-latest]

    runs-on: ${{ matrix.runner }}
    steps:
      - run: sleep 10
      - name: actions/cache@v4
        id: cache-ubicloud
        uses: actions/cache@v4
        with:
          path: test-file 
          key: test-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}

      - name: Generate test file if cache miss
        run: dd if=/dev/urandom of=test-file bs=1M count=1000

      - name: Verify file
        run: | 
          ls -lah test-file
          sha256sum test-file
